version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  node:
    build: .
    ports:
      - '4200:4200'
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - $PWD:/home/app
      - $HOME/.ssh:/home/.ssh
    working_dir: '/home/app'
    user: node
    depends_on:
      - db
    tty: true

volumes:
  db:
  node:
